docs: add DTK-history.md
linuxdeepin/wiki.deepin.org pull request #10
Opened 2023-02-15 07:54 UTC by kegechen

部分修改 https://docsin.uniontech.com/?p=6268

2023-02-15 08:17 UTC, zccrs requested changes

2023-02-15 08:17 UTC, zccrs commented on 01_deepin配套生态/02_deepin深入/01_DTK相关/DTK-history.md
> +# DTK的历史起源、发展，和简单入门
要在头部加一下类似于

````
---
title: DTK(DevelopmentToolKit)
description: DTK(Development ToolKit)）是统信基于Qt开发的一整套简单且实用的通用开发框架，处于统信UOS系统中的核心位置。
published: true
date: 2022-10-18T04:48:31.216Z
tags: 
editor: markdown
dateCreated: 2022-07-13T05:35:13.498Z
---
````
这样的信息

2023-02-15 08:18 UTC, zccrs commented on 01_deepin配套生态/02_deepin深入/01_DTK相关/DTK-history.md
> +# DTK的历史起源、发展，和简单入门
可参考：https://raw.githubusercontent.com/linuxdeepin/wiki.deepin.org/master/01_deepin%E9%85%8D%E5%A5%97%E7%94%9F%E6%80%81/01_deepin%E5%85%A5%E9%97%A8/DTK_DevelopmentToolKit.md

2023-02-15 08:18 UTC, zccrs commented on 01_deepin配套生态/02_deepin深入/01_DTK相关/DTK-history.md
> +# DTK的历史起源、发展，和简单入门
可参考：https://raw.githubusercontent.com/linuxdeepin/wiki.deepin.org/master/01_deepin%E9%85%8D%E5%A5%97%E7%94%9F%E6%80%81/01_deepin%E5%85%A5%E9%97%A8/DTK_DevelopmentToolKit.md

2023-02-15 09:23 UTC, zccrs requested changes

2023-02-15 09:23 UTC, zccrs commented on 01_deepin配套生态/02_deepin深入/01_DTK相关/DTK-history.md
> +description: DTK 的历史起源、发展，和简单入门。
这个才应该是标题吧。这个描述信息一般不会有人看。wiki网页上最明显的是 title 信息。

2023-02-15 09:23 UTC, zccrs commented on 01_deepin配套生态/02_deepin深入/01_DTK相关/DTK-history.md
> +date: 2023-10-18T04:48:31.216Z
这个时间是咋回事

2023-02-15 09:33 UTC, kegechen commented on 01_deepin配套生态/02_deepin深入/01_DTK相关/DTK-history.md
> +date: 2023-10-18T04:48:31.216Z
这个时间显示确实奇怪。。 viewfile就正常
`2023-02-15 17:29:19 UTC`

2023-02-15 09:35 UTC, kegechen commented on 01_deepin配套生态/02_deepin深入/01_DTK相关/DTK-history.md
> +date: 2023-10-18T04:48:31.216Z
date 生成的有点奇怪。参考他的后面加一个216Z 正常

2023-02-16 05:45 UTC, zccrs approved these changes

2023-02-17 03:18 UTC, kegechen commented
/merge

2023-02-17 03:19 UTC, merged